Delete spurious empty file `...`
Delete spurious empty file  `...`. It was causing me trouble cloning this repo on Windows.

> error: unable to create file httpbin/templates/... (Is a directory)
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry the checkout with 'git checkout -f HEAD'